[package]
name = "web_skeleton"
version = "0.1.0"
authors = ["aschuhardt"]

[dependencies]
iron = "=0.5.1"
router = "=0.5.1"
staticfile = "*"
mount = "=0.3.0"
maud = { version = "=0.17.1", features = ["iron"] }
